"""empty message

Revision ID: 00cff889f8de
Revises: 324d6f488bbe
Create Date: 2021-06-19 16:52:39.462238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cff889f8de'
down_revision = '324d6f488bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
