"""empty message

Revision ID: 1d02ec2c6d92
Revises: 84dcebeeec55
Create Date: 2021-02-20 19:34:21.088235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d02ec2c6d92'
down_revision = '84dcebeeec55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
