"""empty message

Revision ID: 324d6f488bbe
Revises: c9d7c868dc68
Create Date: 2021-06-14 20:27:50.113901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324d6f488bbe'
down_revision = 'c9d7c868dc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
