"""empty message

Revision ID: 3dd98f5c161f
Revises: 692f51931284
Create Date: 2021-02-23 16:28:27.448404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd98f5c161f'
down_revision = '692f51931284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('coping_techniques_to_use_before_calling_for_help', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'coping_techniques_to_use_before_calling_for_help')
    # ### end Alembic commands ###
