"""empty message

Revision ID: 607be06ca734
Revises: 44ef8e725244
Create Date: 2021-03-08 22:09:34.034333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607be06ca734'
down_revision = '44ef8e725244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
