"""empty message

Revision ID: 607de81058cf
Revises: ff79287b037f
Create Date: 2021-06-06 16:57:40.731617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '607de81058cf'
down_revision = 'ff79287b037f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('promises_made_to_person', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'promises_made_to_person')
    # ### end Alembic commands ###
