"""empty message

Revision ID: 614817eadf3e
Revises: 1d02ec2c6d92
Create Date: 2021-02-23 07:31:51.000246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614817eadf3e'
down_revision = '1d02ec2c6d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('preferred_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'preferred_name')
    # ### end Alembic commands ###
