"""empty message

Revision ID: 6564c80d1598
Revises: c3c2dc9000d3
Create Date: 2021-06-19 17:03:45.811885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6564c80d1598'
down_revision = 'c3c2dc9000d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
