"""empty message

Revision ID: 796b6133426b
Revises: fc06378bc08f
Create Date: 2021-02-27 09:50:08.684557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b6133426b'
down_revision = 'fc06378bc08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('medication_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'medication_notes')
    # ### end Alembic commands ###
