"""empty message

Revision ID: 84dcebeeec55
Revises: 0dcbcc7debf7
Create Date: 2021-02-20 18:22:00.174211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dcebeeec55'
down_revision = '0dcbcc7debf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
