"""empty message

Revision ID: 8f59b6e9327d
Revises: c5c86c78bed4
Create Date: 2021-06-09 20:20:47.282523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f59b6e9327d'
down_revision = 'c5c86c78bed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'bio')
    # ### end Alembic commands ###
