"""empty message

Revision ID: 9df0dfeb2f53
Revises: f2ee51e84b3c
Create Date: 2021-06-23 09:06:25.706655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9df0dfeb2f53'
down_revision = 'f2ee51e84b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('animals', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('people', 'pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('pets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('people', 'animals')
    # ### end Alembic commands ###
