"""empty message

Revision ID: aad70aa70cbd
Revises: 0dc662fe0d29
Create Date: 2021-06-09 18:32:07.615199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aad70aa70cbd'
down_revision = '0dc662fe0d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bookmarked_people', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bookmarked_people')
    # ### end Alembic commands ###
