"""empty message

Revision ID: ac8af1aa1f14
Revises: 00cff889f8de
Create Date: 2021-06-19 16:53:53.408575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8af1aa1f14'
down_revision = '00cff889f8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
