"""empty message

Revision ID: b52b46aca683
Revises: 614817eadf3e
Create Date: 2021-02-23 07:42:05.612705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52b46aca683'
down_revision = '614817eadf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
