"""empty message

Revision ID: c3c2dc9000d3
Revises: ac8af1aa1f14
Create Date: 2021-06-19 16:55:10.581475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c2dc9000d3'
down_revision = 'ac8af1aa1f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
