"""empty message

Revision ID: c5c86c78bed4
Revises: aad70aa70cbd
Create Date: 2021-06-09 20:13:49.608686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5c86c78bed4'
down_revision = 'aad70aa70cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('diagnoses', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'diagnoses')
    # ### end Alembic commands ###
