"""empty message

Revision ID: c9d7c868dc68
Revises: cbf572551709
Create Date: 2021-06-14 20:05:20.506442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9d7c868dc68'
down_revision = 'cbf572551709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('most_important_contacts', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'most_important_contacts')
    # ### end Alembic commands ###
