"""empty message

Revision ID: ca6d81997be1
Revises: 6fe06f05838e
Create Date: 2021-06-19 19:54:45.938054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6d81997be1'
down_revision = '6fe06f05838e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('persons_email_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'persons_email_address')
    # ### end Alembic commands ###
