"""empty message

Revision ID: cbf572551709
Revises: 8f59b6e9327d
Create Date: 2021-06-11 21:09:01.166671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf572551709'
down_revision = '8f59b6e9327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
