"""empty message

Revision ID: dcbfba4d2197
Revises: 607de81058cf
Create Date: 2021-06-06 17:23:52.864252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcbfba4d2197'
down_revision = '607de81058cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('stressors', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'stressors')
    # ### end Alembic commands ###
