"""empty message

Revision ID: e5c057c152fe
Revises: c62b1f308e3b
Create Date: 2021-02-19 16:49:50.387197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c057c152fe'
down_revision = 'c62b1f308e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'agency')
    # ### end Alembic commands ###
