"""empty message

Revision ID: f2ee51e84b3c
Revises: ca6d81997be1
Create Date: 2021-06-20 20:33:42.468526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2ee51e84b3c'
down_revision = 'ca6d81997be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('religion', sa.String(), nullable=True))
    op.alter_column('people', 'allergies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('people', 'mental_health_conditions')
    op.drop_column('people', 'medical_conditions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('medical_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('people', sa.Column('mental_health_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('people', 'allergies',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('people', 'religion')
    # ### end Alembic commands ###
