"""empty message

Revision ID: fc06378bc08f
Revises: 3dd98f5c161f
Create Date: 2021-02-27 09:28:25.367960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc06378bc08f'
down_revision = '3dd98f5c161f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('mental_health_treatment_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'mental_health_treatment_summary')
    # ### end Alembic commands ###
